### ISSUE TITLE
Settings to disable creation of default object/values in Form Editor

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1222]
As discussed in #1097 - the form editor automatically applies object/property default values defined in the schema - see https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/internals/#handling-of-schema-defaults - which can be annoying/confusing. 

Suggest to add two Project-level "Form Editor Settings" to control this behaviour:
- Create default objects - default false
- Set default primitive values - default true

(Internally we will have to modify the schema passed to the form-editor by removing the corresponding default-values)

**Comment by kingdonb** [comment]
Here's another spin on this issue: I would want a way to disable this behavior at-large because I might use Monokle on repos that I don't own, and it'd be annoying to continually need to revert the changes that I didn't intend before every commit.

On the other hand, as a user who has repos that don't currently include a linter, adopting Monokle presents an opportunity to adopt a linter. So I'd like a way to tell Monokle that it should visit all of my files at once and apply any reformatting/defaults all at once. That way I can commit every "defaults-only, reformat any non-conforming whitespaces" no-op change at once, and rip the band-aid off.

This is actually my feature request, but heavy spoiler alert here: I don't really want users to turn this feature off. It reminds me of `go fmt`, which also reminds me of ruby `standard` and other projects that don't have optional linters, and strongly enforce a single notion of conformance, let's have more of this!
