### ISSUE TITLE
sealed-secrets status error

### ISSUE THREAD

**Issue by pentago** [kubeshop/monokle#1589]
Just noticed that in-cluster sealed-secret display an error saying that the object shouldn't report status for some reason. Why is that?

Screenshot:
![](https://i.imgur.com/8oMSQIE.png)

**Comment by devcatalin** [comment]
Hi @pentago , thanks for reporting this. We have the following list of object paths that are ignored when diffing resources and the same list is used to validate fields that should not exist on local resources:
```
export const CLUSTER_RESOURCE_IGNORED_PATHS = [
  '...creationTimestamp',
  '...lastProbeTime',
  '...finishedAt',
  '...createdAt',
  '...startedAt',
  '...x_kubernetes_preserve_unknown_fields',
  'metadata#annotations#kubectl.kubernetes.io/last-applied-configuration',
  'metadata#annotations#deployment.kubernetes.io/revision',
  'metadata#resourceVersion',
  'metadata#selfLink',
  'metadata#uid',
  'metadata#generation',
  'status',
];
```

Maybe we should offer a way to configure this list or being able to disable the feature.
I think in the screenshot that you've sent above it should definitely be a Warning instead of an Error.
