### ISSUE TITLE
Panel resizing faulty when filter panel is open

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#1635]
When I open the filter panel at the top of the Navigator the resizing logic of the panels is fault; trying to drag the either divider is "sluggish" and only works to the right

**Comment by WitoDelnat** [comment]
Panel resizing has difficulties on multiple fronts:

1. ResizableBox does not nest well in fluid setups.
2. ResizableBox also explicitly requires both width and height which is tedious in fluid environments where we have to resort to a lot of useMeasure and passing heights around to children instead of allowing Grid/Flex to do its thing.
3. ResizableBox uses explicit width instead of percentages, this implicates that we do a lot of calculations in useEffects ourselves to get these percentages. We need multiple effects to reach a correct steady state (with renders that are faulty but that rerender very quickly inbetween).

I want to check with the team if there is something tying us deeply to this library as alternatives work better for setups that are fluid like ours. Below I made a POC with react-reflex, where I first showcase the old behavior and at 0:44 the new library is showcased. I think this is the way forward, but would like to check with the team before spending more time to make sure we align on a solution.

https://user-images.githubusercontent.com/7761005/165111925-2d7ca010-884e-4583-9e61-f02aca515195.mov
