### ISSUE TITLE
Connection to cluster should be named "connect", not "load"

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#2497]
**Describe the bug**
When connecting to a cluster, we show "load", but what we are doing is to connect to the cluster to exctract the objects, and that will depend on customer permissions.

**To Reproduce**

**Expected behavior**
The button should be "connect", after that the "reload" button should be "refresh"
The "exit" button should be renamed "disconnect"

**Screenshots**
<img width="420" alt="image" src="https://user-images.githubusercontent.com/7500590/194117574-b2eb4100-3812-405b-849c-0ed39df4752a.png">

<img width="640" alt="image" src="https://user-images.githubusercontent.com/7500590/194117628-f2c57c38-febd-4dcf-aac4-c1bef116c695.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by devcatalin** [comment]
I think we used the "Connect" label at some point and then decided to rename it to "Load" because we're not opening any connection, just fetching a snapshot of the resources at the moment you click on "load".
When we'll get to implementing the live reload of resources while in Cluster Mode, then it will make more sense to have the label as "Connect".
