### ISSUE TITLE
Update resource updates from Main thread to prevent lagging

### ISSUE THREAD

**Issue by erdkse** [kubeshop/monokle#2724]
**Describe the enhancement you'd like to see**

Currently, whenever a new resource is triggered from the cluster we process it on the main thread and it makes Monokle unreachable. If we process and send new resources to related browser window It will make the application more usable

**Comment by WitoDelnat** [comment]
Just a heads-up, while resource parsing can easily be done in main Electron thread, you will not be able to move validation processing there. Electron refuses to support ESM modules in their Node process because they have too much technical debt to achieve this.

The problem is that the validation library is ESM because we use features such as dynamic imports over HTTP. You can still move that into a web worker for performance (that's what we do in cloud) but it cannot be done in that Node main thread. Apology for the inconvenience!
