### ISSUE TITLE
Use kube proxy for cluster connections

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle#2859]
Several users reported problems connecting with our cluster 

- https://github.com/kubeshop/monokle/issues/1855
- https://github.com/kubeshop/monokle/issues/2203

The problem occurs most often problem in the SSL handshake which is done by the Kubernetes client / NodeJs itself. Unfortunately in all cases the users reported that it works on other tools. Golang is quite liberal with accepting certificates while NodeJs is rather strict as we learned in #1855. The NodeJs Kubernetes SDK is also not officially supported and the fix always has to happen upstream. The best way forward is to eliminate the problem altogether by moving towards a proxy like some other tools do.

**Describe the enhancement you'd like to see**

I'd like Monokle Desktop to start a `kubectl proxy` process in the background. Fetching resources should be done through this proxy which handles all authentication. It's fair to ask a user for their solution to work with `kubectl` and we wont run into the NodeJs related problems anymore. For this solution to work, we'll also have to rewrite the kubeconfig file to connect to the local proxy instead.

**Remarks**

- I tested this approach by starting `kubectl proxy` as a standalone process and manually rewrote the kubeconfig file. This works as expected. The benefit is also that it's less work than initially expected as all NodeJs Kubernetes client logic can remain.
- The biggest challenge is properly starting the proxy. This will be async so we'll have to check if we ever create a Kubernetes client in synchronous code. Afterwards we have to modify the configuration in src/utils/kubeclient.ts:14 which should not be too hard.
- Please ask me for more information about this if you want. We can have a five minute call to go over some nuances I ran into.

**Comment by devcatalin** [comment]
There are some initial things to consider.

If we fail to spawn the kubectl proxy, we should use the user's kubeconfig as a fallback.

We need to decide how to handle changes to the user's kubeconfig and apply them to the proxy kubeconfig.
For example, if the user switches the cluster context, what happens to the proxy?
  - do we have to run `kubectl proxy` again?
  - we will probably have to recreate the proxy kubeconfig if we follow the code example from above, which uses the cluster context name to populate the options

**Comment by devcatalin** [comment]
We should probably spawn the proxy when Monokle starts directly from the main process.
Then, when we have the result from the spawn, either:
  - a working proxy with a proxyUrl as a result
  - an error
      - from the process
      - timeout of the spawning function if no response was received in 10 seconds
      - maybe some logic for retrying to spawn the proxy with different ports

With that result, we'll have to send it to all renderers using `dispatchToAllWindows` which could dispatch an action that will set the proxyUrl to the redux store.
Alternatively, we could store the proxyUrl in a singleton, since reactivity doesn't seem to be important.

The renderers should probably show all cluster operations as loading until we have a response from spawning the proxy.

If we fail to spawn a proxy, we will use the user's kubeconfig that was set to the project.

---

Additionally, we need to keep in mind that the process might error at some point while running or even close.
We should handle those cases and dispatch an action to all renderers to notify to fallback to the user's kubeconfig..
