### ISSUE TITLE
No loading/working indication on comparing local repository and cluster

### ISSUE THREAD

**Issue by fharper** [kubeshop/monokle#2972]
**Describe the enhancement you'd like to see**

When I compare a local folder with my Docker/k3d K8s cluster, it take times, which is normal IMNSHO. During that time though, there is no indication that something is happening. My CPU worked a lot for a while, so I was able to see something was happening because I have a menubar app showing it to me, but even with that, at some point it stopped, but I still had nothing on the interface. Everything worked, but my first thought was that something is wrong with the app, which wasn't the case, and shouldn't be the impression given to people.

A simple solution would be to add a loading spinner, a progress bar, Cortney's head spinning or anything that has motion while this process complete so people knows that there is something happening behind the door.

**Additional context**

https://user-images.githubusercontent.com/1170989/211109927-c89ed0af-ef02-4cd6-8011-cf91b076daee.mp4

**Comment by topliceanurazvan** [comment]
Hey @fharper, for the loading we have the skeleton that appears right after you select a cluster context. Do you find that confusing? Would you rather see some loading spinner instead of it?

**Comment by topliceanurazvan** [comment]
We've added an active Skeleton effect, does this help or do you still think we should still change it to something more significant?

https://user-images.githubusercontent.com/47887589/211298629-7083e9b1-872d-4d49-846d-41a0f41688bd.mp4

**Comment by devcatalin** [comment]
We could also add a small loading icon to the right of the cluster context. @julioramosest what do you think?

**Comment by julioramosest** [comment]
Find UI and UX notes here: https://www.figma.com/file/ttKKFbqVWEPg3BNseXmSsb/Towards-2.0?node-id=1891%3A8423&t=uY7OSavYRrSLRfMG-1

from conversation on the UX meeting: because of implementation constrainments (the UI is process-blocked while loading) no JS animations can be considered at this point. GIF will be tested (attached to this comment - below)

Consistency and other use cases TBD 

![loading and waiting 1](https://user-images.githubusercontent.com/97731654/212960383-cad83081-450d-45e7-9bd5-93c6a2ea2147.png)

the testing GIF bar:

![loading-bar-150px](https://user-images.githubusercontent.com/97731654/212960472-d8020f76-2b20-4702-a6bb-03b12a981e80.gif)
