### ISSUE TITLE
kustomize overlays should be shown with their path

### ISSUE THREAD

**Issue by olensmar** [kubeshop/monokle#3498]
this is the https://github.com/redhat-developer/gitops-repo-example repo - Monokle Cloud shows

<img width="580" alt="image" src="https://user-images.githubusercontent.com/1917063/227207079-e0af1b63-d8d9-46ee-9e70-58ff2b437fc9.png">

whereas desktop shows

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/1917063/227207122-4dd42680-0939-4cf7-be00-57b0aeb5e391.png">

**Comment by chargio** [comment]
This is a problem that has been identified in more places, if the same resource names are reused in different folders, you get different copies of the same resource, and there is no information to distingish them until you click on them (to show the file), making it hard to show

**Comment by olensmar** [comment]
thanks @chargio - this has actually been discussed almost since the beginning - see https://github.com/kubeshop/monokle/issues/424 for some possible solutions - cc @julioramosest

**Comment by julioramosest** [comment]
I would:
- Opt for having the file path next to the name label when hovering (not a tooltip, since that's slower)
- since filepath can be long and first parent folders being the same, I would show only the last 2 folders, this way: **.../folder/folder**
- also truncating full length according to pane width, as we do with other file names
- color for the file path: grey-7

**Comment by olensmar** [comment]
weirdly enough this works like cloud for some repos - for example 

![Image](https://user-images.githubusercontent.com/1917063/230893299-3b963f18-4d59-483a-9d2c-4d37480bc298.png)
