### ISSUE TITLE
Monokle fails to read kubeconfig files that are missing optional parameters

### ISSUE THREAD

**Issue by chargio** [kubeshop/monokle#3511]
Kubeconfig files can have optional parameters that are not required to connect.
Monokle fails to load those files, even if they are correct.

**Comment by mortada-codes** [comment]
@dejanzele can you please try the latest version?

**Comment by WitoDelnat** [comment]
This was already tested with a file Dejan gave. It still will not manage to work with this kind of kubeconfig files since it is the underlying library that requires them. The culprit was a cluster name that was an empty string `""` - this usually only happens if you manually temper with the file and is more an edge case.

Monokle Desktop now clearly indicates the property that has to be filled in so it's easy to get us working with the kubeconfig file.
