### ISSUE TITLE
News feed

### ISSUE THREAD

**Issue by devcatalin** [kubeshop/monokle#3935]
We want to be able to message users with updates, announcements, relevant articles/events, etc. to be shown in-app - either as a notification and/or in some general "Latest News" panel.

Some details:
- the list should be retrieved once on startup and reload automatically every 1 hours
- the https request to retrieve the list should add parameters for os, version, reload (so we can distinguish initial from reload)
- the list should have the following types of entries - with optional "read-more" links
  - Monokle news / announcements
  - General K8s content 
  - ?
- Telemetry for if users click on read-more links 

We need to be able to manage this content on the BE and track nr of downloads - RSS?

**Comment by ayushgml** [comment]
@devcatalin I want to work on this issue and therefore i want to clear the requirements(as per current stated scope):
### Backend:
 - We need to set up a backend endpoint that generates an RSS feed
 - Make the feed with the content, including Monokle news/announcements and general K8s content
### Frontend:
 - Fetch and parse the RSS feed from the backend endpoint.
 - Display the parsed feed items within the app, as notifications and/or in a "Latest News" panel.
 - Implement new UI components to handle the display of feed items and the "read-more" functionality.
 - Telemetry for "read-more".

Please correct me if I am wrong somewhere in my understanding of the issue.
Can I be assigned this issue?

**Comment by olensmar** [comment]
thanks @ayushgml - we still need designs for this from @julioramosest - not sure if he has time for this right now!?

Regarding the BE we haven't figured that one out - still waiting to see if our existing publishing platform (webflow) has sufficient RSS support or if we should use something else. I could mock up an RSS feed for you to get things going if necessary !?

**Comment by ayushgml** [comment]
Hey @olensmar ! No issues if @julioramosest doesn't have time for this. I just wanted to worn on an issue. Could you guide me to any other issue if not this that I can work on?

**Comment by olensmar** [comment]
sure - how about this!? https://github.com/kubeshop/monokle/issues/3695

**Comment by ayushgml** [comment]
Thanks @olensmar ! I will work on this one.

**Comment by julioramosest** [comment]
@ayushgml I'd been planning to have UI design for this one right away - although there are other issues that are getting in the way, more roadmap-centered. I still think I can have UI for this between today and tomorrow. A question @olensmar : what variables are we thinking to define for the RSS? title+description? title only? more (author, feat. image...)?

**Comment by olensmar** [comment]
thanks @julioramosest - let's start with
- title
- description
- url
- timestamp
- tags (helm, kustomize, etc..)
- type (announcement, event, content)

@CortNick any other properties we should include?

**Comment by ayushgml** [comment]
Hey @julioramosest! I will start working on this whenever you are done with the design. @olensmar Once the UI is done I will start working on the UI with some sample content. Once that is done, I will post it here and whenever you get the RSS feed mockup ready, I will continue with the integration. Anything else do I need to know to get started?

**Comment by ayushgml** [comment]
Hey @julioramosest! I think there are pros and cons of both the options:

## Option 1
### Pro
 - Visibility of the top feed post at all times can be a boost for the feed items as user might not click at them
### Con
 - Limited space(vertically).

## Option 2
### Pro
 - Consistency with design as other routes are also there in the side panel.
### Con
 - Discoverability of the feed. Feed posts will be less opened and accessed by users then. 
 
 
My opinion: If I'm thinking the the right direction then the primary purpose of the feed was to increase the discoverability of our feed posts. So to cater that, Option 1 seems to be more fit for the purpose. @olensmar what do you think?

**Comment by olensmar** [comment]
thanks @ayushgml - i agree that discoverability is key - @julioramosest can you think of some way to just display a list of "What's new" items that includes only the title, date, read-more link? We could complement this with a "What's new" left-menu item that opens the full list as in your design!?

**Comment by julioramosest** [comment]
great input @ayushgml and @olensmar! I'm giving it a spin with all of this and some more ideas I've gathered along the way. Hold your horses!

**Comment by olensmar** [comment]
thanks @ayushgml - we're still working out the BE part of this - perhaps @devcatalin has something for you to work on meanwhile?

**Comment by ayushgml** [comment]
Sure @olensmar! I will work whenever the BE part is ready. Meanwhile I will browse other issues till @devcatalin has something else for me.

**Comment by julioramosest** [comment]
@ayushgml @olensmar Habemus RSS UI! We are starting with this module on the top right (see figma below). Some considerations:
- The module needs to be placed in 2 screens: projects screen and new project screen.
- the module has a fixed height according to design. Content scrolls
- No clicking further to see details by now. the module is a stand-alone.
- Number of max items in the feed TBD
- The module is placed in the right column. Current responsiveness in desktop needs to be updated to match what is defined in the figma below. Further responsiveness testing needs to be made when layouted (in dev environment) to ensure it plays nicely in various resolutions. Further decisions can be made on the fly.
- Layouting: observe designed margins out of the box borders, paddings within, spaces between feed news, etc.
- Proper telemetry needs to be also in place, counting not only prints but also unique sessions/users (since the module can load several times in the same session/user)

Figma for the RSS module: https://www.figma.com/file/HOx9fsNedtkR2G0bCpHDX9/Resource-actions%2C-previewing-and-more?type=design&node-id=1106%3A10031&t=T0kOrrdwg3sMgKAf-1
Figma for the responsive layout: https://www.figma.com/file/IdlMEkYijZHpBFQVHt1ch5/Getting-Started---Cloud?type=design&node-id=130%3A1818&t=TrM6M2kxW31LOFtp-1


<img width="1440" alt="RSS 5" src="https://github.com/kubeshop/monokle/assets/97731654/bedec3fb-731f-4885-857f-39e8458ba066">


<img width="1440" alt="responsiveness 1" src="https://github.com/kubeshop/monokle/assets/97731654/a924fb23-af63-4d84-8e61-1f976cb6f23d">

**Comment by olensmar** [comment]
thanks @julioramosest - LGTM!

**Comment by ayushgml** [comment]
Great work @julioramosest! The design looks good!

**Comment by ayushgml** [comment]
Hey @devcatalin @olensmar @julioramosest! Thank you for guiding me! It helps me learn so much from you guys.🙌🏼
Currently, The feed looks like this:


https://github.com/kubeshop/monokle/assets/72748253/19840d2c-a20f-43bd-b858-67dbd851cec7

My further questions:
 - How do I proceed with the telemetry? Where should I send/update the data?
 - What happens to the News feed on width below 844px?

Also, I am yet to do minor styling/padding/gaps minor tweaks for this screen width.
You guys can also mention other changes/inclusions in this. Let's make this top-notch!

**Comment by ayushgml** [comment]
Thank you @julioramosest for the advice and appreciation! Yes I agree that scrollbar should appear only while hovering over the news feed and also thr 500ms transition is necessary to make it a bit smoother. I will implement those changes.

**Comment by olensmar** [comment]
looking good @ayushgml - no telemetry needed for this - just be sure to load the news-feed only once on startup for now..

**Comment by ayushgml** [comment]
Thank you @olensmar! Okay I will make sure the feed loads only once.

**Comment by ayushgml** [comment]
Heyy @julioramosest !! I have a few doubts regarding the UI regarding the behaviour of Start page when we decrease the window width. How should I proceed with the collapse of width of the left menu bar and display of right News Feed?
I think UI change should be kept a bit smoother IMHO. Because from what I observed while developing that as I decreased the width gradually, both news feed and left menu bar are fully visible and bit hidden content overflow occurs at around 1250px even though my device zoom is default. So to tackle the issue I made it look like this:

https://github.com/kubeshop/monokle/assets/72748253/7b0be439-bc50-44e9-8b0b-f4f59d50927f

**Comment by julioramosest** [comment]
@ayushgml I think your decisions just look perfect! Really slick. So on board with them. Make sure none of that affects telemetry. It's important that we track the loading of the feed even if it's hidden (i.e. a user opening the tool on an already narrow resolution). Great work!

**Comment by ayushgml** [comment]
Thank you @julioramosest !! Yes I will make sure to load even though its hidden.

**Comment by olensmar** [comment]
looks great! - could we move the newsfeed to be under the list of projects if it doesn't fit on the side?

**Comment by ayushgml** [comment]
Heyy @olensmar !! Yes we can move the news feed under the list of projects if it doesn't fit on the side. 
@julioramosest how should I proceed with the UI of that case? Suppose a user has many projects so a scrollbar would also be present in projects column. Somewhat like this?:

https://www.figma.com/file/HOx9fsNedtkR2G0bCpHDX9/Resource-actions%2C-previewing-and-more?type=design&node-id=962%3A9122&t=vEhwrPWRHpUcKT6J-1

**Comment by julioramosest** [comment]
@ayushgml I suspect that users that will narrow down a lot their instance they probably also have a limited height, so we are fine with having the element in that case simply at the end of the project list, next to last project, no fixed view. Just another element there, affected by the general scroll.

**Comment by ayushgml** [comment]
Thanks @julioramosest ! I will implement it then just below the last element at the bottom and ask here i I have any doubts regarding the design.

**Comment by olensmar** [comment]
@ayushgml looks fab to me!

**Comment by julioramosest** [comment]
Same to me! hit it @ayushgml

**Comment by ayushgml** [comment]
Thank you @olensmar and @julioramosest!!

**Comment by devcatalin** [comment]
Closing this issue since we released the feature
