### ISSUE TITLE
Back to project when there is a project opened

### ISSUE THREAD

**Issue by topliceanurazvan** [kubeshop/monokle#4054]
Right now when going back to start page if you have a project opened, it's quite hard to notice that you have to go under `Projects` and select your project to go back. We should add a `Back to project` button in the header or something similar.

**Comment by julioramosest** [comment]
@topliceanurazvan My understanding was that once you go to the selection UI it's not like you leave some project "opened". You just choose another one or the same again. Or start a new one. But nothing was like "running" in the background. Sort of like a "linear" workflow. Seems like it's not like that, that you leave a project opened until you open another one? Is that so?

**Comment by topliceanurazvan** [comment]
Exactly, right now if you have a project opened, you go to the start page and then you click on the same one, we have everything already loaded for you, and it will remain the same "in the background". I'm not sure if users might use it like this, but there are some things, like the plugins, that you can edit just by going to the global settings, and you might now want to open another project, but go back to the current one...

**Comment by julioramosest** [comment]
design: https://www.figma.com/file/HOx9fsNedtkR2G0bCpHDX9/Resource-actions%2C-previewing-and-more?type=design&node-id=1051%3A9265&t=RthYcMQQzBc7OyOx-1

Notes:
- it won't appear when opening the app - only user has really a project opened in the session
- since we don't have an action of "closing" a project let's act with care. I think text label is fine this way but can be discussed
- layout: pay attention to arrow icon size, and whole element placement and padding to other elements left and right. 
- A hover effect can be added - a slight change from gray9 to gray8 would make it. Or other.
- 
<img width="1440" alt="back to project" src="https://github.com/kubeshop/monokle/assets/97731654/97d8a11e-d37c-41a1-a430-2a2383046544">
